[project]
name = "orbita2d"
dependencies = ["cffi", "numpy", "pyyaml"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"


[tool.maturin]
python-source = "python"
module-name = "orbita2d._orbita2d"
