[package]
name = "orbita2d_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orbita2d_kinematics = { version = "0.1.0", path = "../orbita2d_kinematics" }
cache_cache = "0.1.0"
rustypot = "0.4.0"
serialport = "4.2.1"
clap = "4.3.8"
