!Flipsky
serial_port:
- /dev/left_elbow_A
- /dev/left_elbow_B
ids:
- 73
- 74
motors_offset:
- 0.0
- 0.0
motors_ratio:
- 96.691
- 96.691
inverted_axes:
- false
- false
orientation_limits: null
use_cache: false
