!Flipsky
serial_port:
- /dev/left_shoulder_A
- /dev/left_shoulder_B
ids:
- 83
- 84
motors_offset:
- 0.0
- 0.0
motors_ratio:
- 96.691
- 96.691
inverted_axes:
- false
- false
orientation_limits: null
use_cache: false
