!Flipsky
serial_port:
- /dev/right_elbow_A
- /dev/right_elbow_B
ids:
- 71
- 72
motors_offset:
- 0.0
- 0.0
motors_ratio:
- 96.691
- 96.691
inverted_axes:
- true
- false
orientation_limits: null
use_cache: false
