!Flipsky
serial_port:
- /dev/right_shoulder_A
- /dev/right_shoulder_B
ids:
- 81
- 82
motors_offset:
- 0.0
- 0.0
motors_ratio:
- 96.691
- 96.691
inverted_axes:
- true
- false
orientation_limits: null
use_cache: false
