name: Python checks

on: [push]

jobs:
    maturin:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
  
      - name: Deps
        run: |
          sudo apt-get update
          sudo apt install -y libudev-dev
  
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin cffi

      - name: Run maturin
        run: |
          cd orbita2d_c_api
          maturin build
          pip install ../target/wheels/*.whl
    
  