name: Python checks

on: [push]

jobs:
    maturin:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
  
      - name: Deps
        run: |
          sudo apt-get update
          sudo apt install -y libudev-dev
  
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin cffi pytest

      - name: Run maturin
        run: |
          cd orbita2d_c_api
          maturin build
          pip install ../target/wheels/*.whl
    
      - name: Run tests
        run: |
          cd orbita2d_c_api/python
          python -m pytest

      - name: Run flkake8
        run: |
          cd orbita2d_c_api/python
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude orbita2d/_orbita2d
          # option --exit-zero can be added to this line to set these errors as warnings
          flake8 . --count --max-complexity=10 --max-line-length=128 --statistics --exclude orbita2d/_orbita2d
  