name: Python checks

on: [push]

jobs:
    python-tests:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v3
  
      - name: Deps
        run: |
          sudo apt-get update
          sudo apt install -y libudev-dev
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install maturin cffi pytest

      - name: Run maturin
        run: |
          cd orbita2d_c_api
          maturin develop
          pip install ../target/wheels/*.whl
          python -c "import orbita2d"
    
